### ISSUE TITLE
[Need to Repair As Soon] 在部分情况下，切换卡将导致整体字体渲染异常（渲染为注释绿）

### ISSUE THREAD

**Issue by MarsTechHAN** [nodemcu/nodemcu-studio-csharp#11]

**Comment by jiegec** [comment]
如何出现？

**Comment by MarsTechHAN** [comment]
@jiegec 打开两个文件...
![image](https://cloud.githubusercontent.com/assets/10462805/6752786/3c9b0242-cf4c-11e4-814f-604247613511.png)
