### ISSUE TITLE
[Advice]读取最好直接读取，而不是输入名字

### ISSUE THREAD

**Issue by MarsTechHAN** [nodemcu/nodemcu-studio-csharp#15]
![image](https://cloud.githubusercontent.com/assets/10462805/6752743/e683d6fe-cf4b-11e4-82cd-e2b086e5e046.png)

**Comment by jiegec** [comment]
那么有多个文件呢

**Comment by MarsTechHAN** [comment]
@jiegec file.lise()返回的是table
