### ISSUE TITLE
[Need to Repair As Soon] Console need to scroll-able 

### ISSUE THREAD

**Issue by MarsTechHAN** [nodemcu/nodemcu-studio-csharp#5]
Suggest to use FCTB

**Comment by MarsTechHAN** [comment]
@jiegec 你Close ISSUE的时候，最好加上什么版本修正的，比如说 #9

**Comment by MarsTechHAN** [comment]
@jiegec 能用个FCTB不= =

**Comment by MarsTechHAN** [comment]
@jiegec 能用个FCTB不= =

**Comment by jiegec** [comment]
https://github.com/nodemcu/nodemcu-studio-csharp/commit/c5cfb8140cb658747c8547125f758cffc659d5af
