### ISSUE TITLE
一旦串口关闭，无法再打开，没有打开串口按钮，下载/运行等按钮变灰

### ISSUE THREAD

**Issue by nodemcu** [nodemcu/nodemcu-studio-csharp#8]
一旦串口关闭，无法再打开，没有打开串口按钮，下载/运行等按钮变灰

**Comment by MarsTechHAN** [comment]
Fatal Error Confirm...Start-> #9

**Comment by MarsTechHAN** [comment]
![image](https://cloud.githubusercontent.com/assets/10462805/6763533/cd1be25e-cfbb-11e4-82e4-4e966f755c4b.png)
Cannot Connect to device后

**Comment by jiegec** [comment]
should be fixed now
